### ISSUE TITLE
Chat regarding next newsletter

### ISSUE THREAD

**Issue by kelvinsekx** [kelvinsekx/IBTC-html-template#1]
Hi kindly comment, watch, and fork this repo

**Comment by okunlolafz** [comment]
Noted 👍

**Comment by kelvinsekx** [comment]
We are waiting for the last guy. Sorry I've not mastered you guyz name.

Okunlola I also want to believe you've read a number of the previous newsletter from the archives.

**Comment by kelvinsekx** [comment]
If you've got any tech gist or something trending and it's tech-ish you can simply share them here.

**Comment by okunlolafz** [comment]
Alright! I will be sure to do that.

And yes, I've read a couple of the previous newsletters.

**Comment by kelvinsekx** [comment]
Here is one trending gist
https://techcabal.com/2022/08/29/risevest-ceo-asked-to-step-down-due-to-allegations-of-sexual-and-non-sexual-misconduct/?utm_source=dlvr.it&utm_medium=linkedin

Risevest CEO got indulged in some case of sexual assault.

**Comment by EarlPappi** [comment]
Here finally, LFG

**Comment by kelvinsekx** [comment]
Thanks.
We couldn't send newsletter today until next week Friday.

However, on Monday we would send a newsletter telling everyone about the new changes to team and those who will be writing it henceforth.

And then on Friday we will send the first newsletter after a long time.

**Comment by kelvinsekx** [comment]
Please provide a short introduction of yourself not more than 30 words that would be used on the introduction newsletter on Monday.

**Comment by okunlolafz** [comment]
I am Okunlola Faozee, undergraduate student of Mechanical Engineering, University of Ibadan. I am a 3D artist, Game Developer and I have keen interests in AI/ML as well as other Tech related fields.

**Comment by EarlPappi** [comment]
I am Aponjolosun Miracle, a student of university of Ibadan. I’m a frontend developer and Table tennis is in love with me.

**Comment by kelvinsekx** [comment]
Unfortunately today's call couldn't hold due to clashes in times.

**Comment by kelvinsekx** [comment]
I'll highlight what I intended to talk about
1. We should learn to acknowledge when we read a message. A simple emoji reaction is enough.
2. We should always try to reply any message addressed to us with 24hrs. If it is something that requires an action that can't be achieved in the said time, let us know when you would reply.

**Comment by okunlolafz** [comment]
Noted with thanks!

**Comment by kelvinsekx** [comment]
I just wrote a bare bone of today's newsletter.
It is intended to introduce the fresh faces to our subscribers
https://github.com/kelvinsekx/IBTC-html-template/blob/2-write-introduction-template-for-monday-5th-september-2022/MondayEmergencyEdition.md

Have a read.

**Comment by EarlPappi** [comment]
> 

Alright boss, we’ll do better

**Comment by EarlPappi** [comment]
> I just wrote a bare bone of today's newsletter. It is intended to introduce the fresh faces to our subscribers https://github.com/kelvinsekx/IBTC-html-template/blob/2-write-introduction-template-for-monday-5th-september-2022/MondayEmergencyEdition.md
> 
> Have a read, make corrections if you have any, I'll be posting this newsletter by 5pm.

I read through this and it’s great, I’ll give it another read to check for typo tho 🌚

**Comment by okunlolafz** [comment]
It's great!

**Comment by kelvinsekx** [comment]
Congratulations 🎉 on our Monday newsletter, more or less not a newsletter.

Friday is another day.
Please if there is any tech gist you, please share us the link.

Also, what aspect of the newsletter you would love to write?

**Comment by kelvinsekx** [comment]
No one responded to my last comment.
Do you guyz really think you are interested in this newsletter?

If you've all got something important and can't spare some minutes of your time. Please let me.

**Comment by kelvinsekx** [comment]
It isn't funny that even with 3 hands, it as if we still have one person, myself in charge.

If I don't get a response in 24hrs to this comment though,
I'll regard it as a conclusion of unavailability, and revert the newsletter authors.

Best regards.

**Comment by EarlPappi** [comment]
I still haven’t gotten the hang of how things will be, so I’m currently just observing

I’ll suggest you assign task  as I’m honestly currently clueless on what to do

**Comment by kelvinsekx** [comment]
Okay I'll assign tasks tomorrow.
Also whatever story you write, it has to be short and with some links.

**Comment by okunlolafz** [comment]
Yeah! Got it

**Comment by kelvinsekx** [comment]
I just created some issues you can pickup.
Tomorrow I'll be closing this issue to create another chat issue for the week.

**Comment by okunlolafz** [comment]
Talk of national insecurities among tech-giant countries!
Why is the United States always troubled when it comes to technology race against China?
Last month, $280bn was committed to high tech manufacturing and scientific research by the US President just because of the fear of losing technological edge to China. Statistics says from 1990 up till now, the US global supply of semiconductors went from nearly 40% all the way down to 10%. Semiconductors being the key ingredients to manufacturing products ranging from mobile phones to cars.
Like this was not enough, the US has just made more implementations to reduce leading edge technological investments and reliance on China. 
“US tech companies that receive federal funding will be barred from building "advanced technology" facilities in China for 10 years”, the Biden administration has said.”

https://www.bbc.com/news/62803224.amp

https://youtu.be/OsBcMxDwZSM

I can only wonder why my country did not enrol in this competition? 🥲 Did we forget to register or something?

**Comment by okunlolafz** [comment]
So this is it, 
I will be anticipating your comments/adjustments and the expected line of action. Thanks

**Comment by kelvinsekx** [comment]
> So this is it, I will be anticipating your comments/adjustments and the expected line of action. Thanks

This is awesome 🎉.
Can you pick this issues and add anyother gist there
https://github.com/kelvinsekx/IBTC-html-template/issues/3.

**Comment by okunlolafz** [comment]
Okay! Will do.

**Comment by EarlPappi** [comment]
Can I go with this new ETH merge, im in a way into NFT and this new ETH merge meant a lot to upcoming project

Is that something worth writing about?!

**Comment by EarlPappi** [comment]
I already thought of a title already 😹😹😹

ETH Merge - WAGMI?! 

Awaiting your thoughts too

**Comment by okunlolafz** [comment]
sounds interesting 👍

**Comment by kelvinsekx** [comment]
Yeah, why not.
You can write about it.
Remember to keep it short and add links to affirm your claims.

Also, every write-up should be submitted before 12pm... I'll be sending the newsletter by 4pm.
