### ISSUE TITLE
Tech gist between Sept 1st and 14tg

### ISSUE THREAD

**Issue by kelvinsekx** [kelvinsekx/IBTC-html-template#3]
The gists or trending news should not be more than 3 in number.

**Comment by okunlolafz** [comment]
Acknowledged sir.

**Comment by okunlolafz** [comment]
Core Developers! All eyes on docs now

Official release of Python 3.11 is planned for Monday, 24th October, 2022 following the released second candidate (3.11.0rc2) and last planned release preview in the 3.11 series.
Don't get too excited, 3.11.0rc2 is a preview release and is not recommended for production environments. However, from this point forward, there will be no ABI changes and the goal is that there will be as few codes changes as possible.
https://www.python.org/downloads/release/python-3110rc2/

Want to hear what's even exciting? 😁Pay attention to the release trends, no doubts, there's been significant increase in Python runtime speed. Compare with C++ and be marveled.

According to an analysis by Dennis Bakhus, possibility is that Python 3.14 will be faster than C++. Absolutely ridiculous, isn't it?😂 I hope you find it worth reading 🤗👇
https://technoblender.com/python-3-14-will-be-faster-than-c-by-dennis-bakhuis-sep-2022/

**Comment by kelvinsekx** [comment]
I feel we will send the newsletter tomorrow and apologize.

Seems like I'm dead busy to send a newsletter today.

**Comment by kelvinsekx** [comment]
Nothing spoil.
