### ISSUE TITLE
newsletter #20

### ISSUE THREAD

**Issue by Iykee** [kelvinsekx/IBTC-html-template#8]
**### Club Gist**

Hi Techie!!!
 It's another friday and we are super excited to publish another issuse of our news letter. It's been awhile since our last publication, we have been working behind the scenes to ensure we serve you better.
 We had our last meetup for the year on Saturday 26th November 2022, we were privileged to be joined by club backers 
    Jason Palmer and Ije they spoke about 

> "Product thinking for Engineers"

 and 

> "Being a black woman in tech respectively" 

     other speakers were David who spoke about overcoming imposter Syndrome and Kishii spoke about Her Journey Into Software development.
    2022 has been a really exciting year for the club we had  meetup( both technical and general meetup ).
    we had lots of exceptional speakers who talked to us abouts exciting and educative topics. Members of the club have
    also had the opportunity  to network and learn. We want to use this opportunity to thank all our Sponsors and members for makeing 
    2022 a success. Plans are already being made to ensure we serve you better next year.

**### HE WEEK GIST IN REVIEW**
   
  **### Elon Musk's Twitter cannot stay out of the news**
Since the acquisition of Twitter by billionaire Elon Musk, the social media company has always been in the news. The latest one being 
#twitterfiles
Twitter files is a group of classified twitter documents being released  by Elon Musk in collaboration with some top journalist. 
Twitter files sherd light on some user moderation and censoring  decisions taken by the company over the years.
The most notable among them was the decision to permanently ban former US president Donald Trump on January 8th 2021 for 'inciting Violence'
Evidence from some of the twitter files released shows that top executives working at twitter at that time did not believe that Donald Trumps tweet went against the company's policies or incited violence.
The document reveals that the ban on Trumps twitter account was mostly due to pressure from within and outside Twitter. The files have sparked debates online some people believe that Twitter made the right decision by banning Trumps account while others believe the social media giant crossed a line they shouldn't have
you can read some of the debates [here](uhttps://twitter.com/search?q=twitter%20files%20summary&src=typed_query&f=toprl)

 ### **Is ChatGpt coming for our jobs?**

   ChatGPT is a prototype artificial intelligence chatbot developed by OpenAI. OpenAI is an artificial intelligence laboratory in San Francisco Founded by  y Sam Altman, Elon Musk, and others.
   Elon Musk seems to be everywhere.
   So back to ChatGpt since the launch of the prototype in november social media especially Twitter has been agog with some of the amazing things this chatbot can do.
   A twitter user @volodarik wrote  and I quote 

> " ChatGPT has crossed 1M+ users in just 5 days. 
> 
>    To compare, it took Netflix 41 months, FB - 10 months, and Instagram - 2.5 months. 
>    
>    But many haven’t yet realized its full potential.
>    
>    Here are the 10 mind blowing things you can do using it right now:
> 1/ Generate code
>  
>    ChatGPT can help you generate code to build your app/website from scratch.
>     
>    You save time and effort and can focus on the more important tasks.
>     
>    100X engineer just arrived 
>    2/ Track fitness
>  
> Alex created a weight loss, diet, and workout plan on top of ChatGPT. 
> 3/ Debug code
>  
> ChatGPT is your 24/7 debugging companion. It finds the bugs, fixes them, and even explains the solution
> 4/ Have a personal assistant
>  
> Integrate ChatGPT to your WhatsApp and automate the manual and repetitive tasks: write emails, get quick answers to any questions, fasten research, and more.<br>
> 5/ Marketing Plan
>  
> Create a marketing/SEO strategy, audit your website, do keyword research, write articles/copy, and more—all in less than 30 minutes.
> 6/ Create a Virtual Machine
>  
> Research Scientist Jonas Degrave ran a virtual machine (Linux terminal) inside ChatGPT.
> 7/ Creative liberty
>  
> Write essays, music, sitcom/movie scripts, and jokes.<br>
> 8/ Develop plugins
>  
> ChatGPT created a working WordPress plugin on the first try.
> 
> 9/ Game development
>  
> An 11-year-old developed a game using the ChatGPT prompts. Thousands of people have already played it.
> 10/ Medical aid
>  
> You can develop a 24/7 chatbot to seek treatments for a few medical problems.
>  
> Of course, as mentioned below, you need to check for biases and misinformation, but this is a good start."

As you can expect this tweet generated a lot a reactions with most users claiming that AI will take over a lot of tech jobs in the future while others were of the Opinion that AI will not necessarily take over tech jobs but will make them easier.
Personally I believe that Humans will always be Superior and Ai cannot fully take over tech jobs. One tweet I saw which I really love basically says "ChatGpt will take the jobs of those who believe it will take over their jobs". I feel developers should just focus on Upskilling One way or the other your services will be needed.

**Comment by kelvinsekx** [comment]
@Iykee  😂 thanks for the effort you put into this post. This is really awesome man.
